on:
  workflow_run:
    workflows: ["VHDL testbench"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      
      
      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install gperf build-essential bison flex libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot pkg-config python python3 libboost-system-dev libboost-python-dev libboost-filesystem-dev zlib1g-dev
      - name: Get iverilog
        shell: bash
        run: |
          git clone https://github.com/steveicarus/iverilog.git

      - name: Cache iverilog
        id: cache-iverilog
        uses: actions/cache@v3
        with:
          path: .local/
          key: ${{ matrix.os.id }}-${{ hashFiles('iverilog/.git/refs/heads/master') }}

      - name: Build iverilog
        if: steps.cache-iverilog.outputs.cache-hit != 'true'
        shell: bash
        run: |
          mkdir -p $GITHUB_WORKSPACE/.local/
          cd iverilog
          autoconf
          CC=gcc CXX=g++ ./configure --prefix=$GITHUB_WORKSPACE/.local
          make -j${{ env.procs }}
          make install

      - name: Build yosys
        shell: bash
        run: |
          CC=gcc
          make config-$CC
          make -j${{ env.procs }} CC=$CC CXX=$CC LD=$CC
      
      - uses: actions/checkout@v3
      - name: Generate Verilog code
        run: |
           for unit in adder full_adder; do echo $unit; done
