name: Generate Verilog code

on:
  workflow_run:
    workflows: ["VHDL testbench"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      
      
      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install gperf build-essential bison flex libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot pkg-config python2 python3 libboost-system-dev libboost-python-dev libboost-filesystem-dev zlib1g-dev iverilog


      - name: Restore cached Yosys build
        id: cache-yosys-restore
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/yosys/
          key: yosys

      - name: Fetch yosys
        if: steps.cache-yosys-restore.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/YosysHQ/yosys.git
      
      - name: Build yosys
        if: steps.cache-yosys-restore.outputs.cache-hit != 'true'
        shell: bash
        timeout-minutes: 20
        run: |
          cd yosys
          echo ${{ github.workspace }}
          pwd;#exit
          CC=gcc
          make config-$CC
          free -h
          #make -j${{ env.procs }} CC=$CC CXX=$CC LD=$CC  # OOM killed?
          make -j2 CC=$CC CXX=$CC LD=$CC


      - name: Save cached Yosys build
        id: cache-yosys-save
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/yosys/
          key: ${{ steps.cache-yosys-restore.outputs.cache-primary-key }}


          
      - uses: actions/checkout@v3
      - name: Generate Verilog code
        run: |
           for unit in adder full_adder; do echo $unit; done
