on:
  workflow_run:
    workflows: ["VHDL testbench"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test
        run: echo "OKAY"
